ACTIVITY_TAGS = [
    "Prep Cover Letter",
    "Prep Resume",
    "Reach Out", 
    "Get Reference", 
    "Apply",
    "Follow Up",
    "Prep for Interview",
    "Phone Screen",
    "Phone Interview",
    "On Site Interview",
    "Offer Received",
    "Accept Offer",
    "Decline Offer",
    "Rejected",
    "Send Thank You",
    "Email",
    "Meeting",
    "Phone Call",
    "Send Availability",
    "Assignment",
    "Networking Event",
    "Other",
    "Application Withdrawn"
]
